angular.module("myApp", [ "angularBeans",'pikaday' ])
// .controller("MyCtrl",MyCtrl)
.controller("AuthentificationCtrl", AuthentificationCtrl)
.controller("MvmPrixCtrl", MvmPrixCtrl)
.controller("UserCtrl", UserCtrl)
.controller("UtilisateurCtrl", UtilisateurCtrl)
.controller("MvmntPrixSejourCtrl", MvmntPrixSejourCtrl)
.controller("MvmntPrixVolCtrl1", MvmntPrixVolCtrl1)
.controller("AjouterArrCtrl", AjouterArrCtrl)
.controller("MvmntPrixVolCtrl", MvmntPrixVolCtrl)
.controller("AjouterHCtrl",AjouterHCtrl)
.controller("AjouterTypeChmCtrl",AjouterTypeChmCtrl)
.controller("AjouterPeriodeCtrl",AjouterPeriodeCtrl)
.controller("AjouterClassVCtrl",AjouterClassVCtrl)
.controller("AjouterACtrl", AjouterACtrl);
