package com.worldsoft.domain;
// Generated 1 avr. 2016 15:12:05 by Hibernate Tools 4.3.1.Final

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinColumns;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * MvmentPrix generated by hbm2java
 */
@Entity
@Table(name = "MVMENT_PRIX")
public class MvmentPrix implements java.io.Serializable {

	/**
	 * 
	 */

	private static final long serialVersionUID = 1L;

	@Override
	public String toString() {
		return "MvmentPrix [idPrix=" + idPrix + ", arrangement=" + arrangement + ", hotel=" + hotel + ", refTiers="
				+ refTiers + ", jour=" + jour + ", periode=" + periode + ", typeChambre=" + typeChambre + ", avion="
				+ avion + ", typeVol=" + typeVol + ", classVol=" + classVol + ", prixAchat=" + prixAchat + ", marge="
				+ marge + ", txMarge=" + txMarge + ", prixVente=" + prixVente + ", actifPrix=" + actifPrix
				+ ", dateRes=" + dateRes + ", dep=" + dep + ", arr=" + arr + ", nbreChm=" + nbreChm + ", villeDest="
				+ villeDest + ", paysDest=" + paysDest + ", flag=" + flag + ", idAvion=" + ", numVol=" + numVol
				+ ", idHotel=" + idHotel + ", idArrangement=" + idArrangement + ", idClassVol=" + idClassVol
				+ ", idPeriode=" + idPeriode + ", idChm=" + idChm + ", horrairedepart=" + horraireDepart + ", dureeVol="
				+ dureeVol + ", volSegment=" + volSegment + ", escale=" + escale + ", getIdPrix()=" + getIdPrix()
				+ ", getArrangement()=" + getArrangement() + ", getHotel()=" + getHotel() + ", getRefTiers()="
				+ getRefTiers() + ", getJour()=" + getJour() + ", getPeriode()=" + getPeriode() + ", getTypeChambre()="
				+ getTypeChambre() + ", getAvion()=" + getAvion() + ", getTypeVol()=" + getTypeVol()
				+ ", getClassVol()=" + getClassVol() + ", getPrixAchat()=" + getPrixAchat() + ", getMarge()="
				+ getMarge() + ", getTxMarge()=" + getTxMarge() + ", getPrixVente()=" + getPrixVente()
				+ ", getActifPrix()=" + getActifPrix() + ", getDateRes()=" + getDateRes() + ", getDep()=" + getDep()
				+ ", getArr()=" + getArr() + ", getNbreChm()=" + getNbreChm() + ", getVilleDest()=" + getVilleDest()
				+ ", getFlag()=" + getFlag() + ", getPaysDest()=" + getPaysDest() + ", getIdArrangement()="
				+ getIdArrangement() + ", getIdPeriode()=" + getIdPeriode() + ", getIdChm()=" + getIdChm()
				+ ", getIdHotel()=" + getIdHotel() + ", getDureeVol()=" + getDureeVol() + ", getVolSegment()="
				+ getVolSegment() + ", getEscale()=" + getEscale() + ", getIdAvion()=" + ", getNumVol()=" + getNumVol()
				+ ", getIdClassVol()=" + getIdClassVol() + ", getClass()=" + getClass() + ", hashCode()=" + hashCode()
				+ ", toString()=" + super.toString() + "]";
	}

	private BigDecimal idPrix;
	private Arrangement arrangement;
	private Hotel hotel;
	private RefTier refTiers;
	private Jour jour;
	private Periode periode;
	private TypeChambre typeChambre;
	private Avion avion;
	private TypeVol typeVol;
	private ClassVol classVol;
	private BigDecimal prixAchat;
	private BigDecimal marge;
	private BigDecimal txMarge;
	private BigDecimal prixVente;
	private Character actifPrix;
	private Date dateRes;
	private String dep;
	private String arr;
	private BigDecimal nbreChm;
	private String villeDest;
	private String paysDest;
	private Character flag;
	private String numVol;
	private long idHotel;
	private long idArrangement;
	private long idClassVol;
	private long idPeriode;
	private long idChm;
	private String horraireDepart;
	private String dureeVol;
	private String volSegment;
	private String escale;

	public MvmentPrix() {
	}

	public MvmentPrix(BigDecimal idPrix, Jour jour, Periode periode) {
		this.idPrix = idPrix;
		this.jour = jour;
		this.periode = periode;
	}

	
	public MvmentPrix(BigDecimal idPrix, Arrangement arrangement, Hotel hotel, RefTier refTiers, Jour jour,
			Periode periode, TypeChambre typeChambre, Avion avion, TypeVol typeVol, ClassVol classVol,
			BigDecimal prixAchat, BigDecimal marge, BigDecimal txMarge, BigDecimal prixVente, Character actifPrix,
			Date dateRes, String dep, String arr, BigDecimal nbreChm, String villeDest, String paysDest, Character flag,
			String numVol, long idHotel, long idArrangement, long idClassVol, long idPeriode, long idChm,
			String horraireDepart, String dureeVol, String volSegment, String escale) {
		super();
		this.idPrix = idPrix;
		this.arrangement = arrangement;
		this.hotel = hotel;
		this.refTiers = refTiers;
		this.jour = jour;
		this.periode = periode;
		this.typeChambre = typeChambre;
		this.avion = avion;
		this.typeVol = typeVol;
		this.classVol = classVol;
		this.prixAchat = prixAchat;
		this.marge = marge;
		this.txMarge = txMarge;
		this.prixVente = prixVente;
		this.actifPrix = actifPrix;
		this.dateRes = dateRes;
		this.dep = dep;
		this.arr = arr;
		this.nbreChm = nbreChm;
		this.villeDest = villeDest;
		this.paysDest = paysDest;
		this.flag = flag;
		this.numVol = numVol;
		this.idHotel = idHotel;
		this.idArrangement = idArrangement;
		this.idClassVol = idClassVol;
		this.idPeriode = idPeriode;
		this.idChm = idChm;
		this.horraireDepart = horraireDepart;
		this.dureeVol = dureeVol;
		this.volSegment = volSegment;
		this.escale = escale;
	}

	@Id

	@Column(name = "ID_PRIX", nullable = false, precision = 22, scale = 0)
	public BigDecimal getIdPrix() {
		return this.idPrix;
	}

	public void setIdPrix(BigDecimal idPrix) {
		this.idPrix = idPrix;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({ @JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL"),
			@JoinColumn(name = "ID_ARRANGEMENT", referencedColumnName = "ID_ARRANGEMENT") })
	public Arrangement getArrangement() {
		return this.arrangement;
	}

	public void setArrangement(Arrangement arrangement) {
		this.arrangement = arrangement;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_HOTEL", insertable = false, updatable = false)
	public Hotel getHotel() {
		return this.hotel;
	}

	public void setHotel(Hotel hotel) {
		this.hotel = hotel;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_REF_TIERS")
	public RefTier getRefTiers() {
		return this.refTiers;
	}

	public void setRefTiers(RefTier refTiers) {
		this.refTiers = refTiers;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_JOUR", nullable = false)
	public Jour getJour() {
		return this.jour;
	}

	public void setJour(Jour jour) {
		this.jour = jour;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL", insertable = false, updatable = false),
			@JoinColumn(name = "ID_PERIODE", referencedColumnName = "ID_PERIODE", insertable = false, updatable = false) })
	public Periode getPeriode() {
		return this.periode;
	}

	public void setPeriode(Periode periode) {
		this.periode = periode;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_HOTEL", referencedColumnName = "ID_HOTEL", insertable = false, updatable = false),
			@JoinColumn(name = "ID_CHM", referencedColumnName = "ID_CHM", insertable = false, updatable = false) })
	public TypeChambre getTypeChambre() {
		return this.typeChambre;
	}

	public void setTypeChambre(TypeChambre typeChambre) {
		this.typeChambre = typeChambre;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_AVION")
	public Avion getAvion() {
		return this.avion;
	}

	public void setAvion(Avion avion) {
		this.avion = avion;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "ID_TYPE_VOL")
	public TypeVol getTypeVol() {
		return this.typeVol;
	}

	public void setTypeVol(TypeVol typeVol) {
		this.typeVol = typeVol;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumns({
			@JoinColumn(name = "ID_AVION", referencedColumnName = "ID_AVION", insertable = false, updatable = false),
			@JoinColumn(name = "ID_CLASS_VOL", referencedColumnName = "ID_CLASS_VOL", insertable = false, updatable = false) })
	public ClassVol getClassVol() {
		return this.classVol;
	}

	public void setClassVol(ClassVol classVol) {
		this.classVol = classVol;
	}

	@Column(name = "PRIX_ACHAT", precision = 22, scale = 0)
	public BigDecimal getPrixAchat() {
		return this.prixAchat;
	}

	public void setPrixAchat(BigDecimal prixAchat) {
		this.prixAchat = prixAchat;
	}

	@Column(name = "MARGE", precision = 22, scale = 0)
	public BigDecimal getMarge() {
		return this.marge;
	}

	public void setMarge(BigDecimal marge) {
		this.marge = marge;
	}

	@Column(name = "TX_MARGE", precision = 22, scale = 0)
	public BigDecimal getTxMarge() {
		return this.txMarge;
	}

	public void setTxMarge(BigDecimal txMarge) {
		this.txMarge = txMarge;
	}

	@Column(name = "PRIX_VENTE", precision = 22, scale = 0)
	public BigDecimal getPrixVente() {
		return this.prixVente;
	}

	public void setPrixVente(BigDecimal prixVente) {
		this.prixVente = prixVente;
	}

	@Column(name = "ACTIF_PRIX", length = 1)
	public Character getActifPrix() {
		return this.actifPrix;
	}

	public void setActifPrix(Character actifPrix) {
		this.actifPrix = actifPrix;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "DATE_RES", length = 7)
	public Date getDateRes() {
		return this.dateRes;
	}

	public void setDateRes(Date dateRes) {
		this.dateRes = dateRes;
	}

	@Column(name = "DEP", length = 3)
	public String getDep() {
		return this.dep;
	}

	public void setDep(String dep) {
		this.dep = dep;
	}

	@Column(name = "ARR", length = 3)
	public String getArr() {
		return this.arr;
	}

	public void setArr(String arr) {
		this.arr = arr;
	}

	@Column(name = "NBRE_CHM", precision = 22, scale = 0)
	public BigDecimal getNbreChm() {
		return this.nbreChm;
	}

	public void setNbreChm(BigDecimal nbreChm) {
		this.nbreChm = nbreChm;
	}

	@Column(name = "VILLE_DEST", length = 30)
	public String getVilleDest() {
		return this.villeDest;
	}

	public void setVilleDest(String villeDest) {
		this.villeDest = villeDest;
	}

	@Column(name = "FLAG", length = 1)
	public Character getFlag() {
		return this.flag;
	}

	public void setFlag(Character flag) {
		this.flag = flag;
	}

	@Column(name = "PAYS_DEST")
	public String getPaysDest() {
		return paysDest;
	}

	public void setPaysDest(String paysDest) {
		this.paysDest = paysDest;
	}

	@Column(name = "ID_ARRANGEMENT", updatable = false, insertable = false)
	public long getIdArrangement() {
		return idArrangement;
	}

	public void setIdArrangement(long idArrangement) {
		this.idArrangement = idArrangement;
	}

	@Column(name = "ID_PERIODE")
	public long getIdPeriode() {
		return idPeriode;
	}

	public void setIdPeriode(long idPeriode) {
		this.idPeriode = idPeriode;
	}

	@Column(name = "ID_CHM")
	public long getIdChm() {
		return idChm;
	}

	public void setIdChm(long idChm) {
		this.idChm = idChm;
	}

	@Column(name = "ID_HOTEL", updatable = false, insertable = false)
	public long getIdHotel() {
		return idHotel;
	}

	public void setIdHotel(long idHotel) {
		this.idHotel = idHotel;
	}

	@Column(name = "DUREE_VOL")
	public String getDureeVol() {
		return dureeVol;
	}

	public void setDureeVol(String dureeVol) {
		this.dureeVol = dureeVol;
	}

	@Column(name = "ID_VOL_SEGMENT")
	public String getVolSegment() {
		return volSegment;
	}

	public void setVolSegment(String volSegment) {
		this.volSegment = volSegment;
	}
	@Column(name = "ESCALE")
	public String getEscale() {
		return escale;
	}

	public void setEscale(String escale) {
		this.escale = escale;
	}

	@Column(name = "NUM_VOL")
	public String getNumVol() {
		return numVol;
	}

	public void setNumVol(String numVol) {
		this.numVol = numVol;
	}

	@Column(name = "ID_CLASS_VOL")
	public long getIdClassVol() {
		return idClassVol;
	}

	public void setIdClassVol(long idClassVol) {
		this.idClassVol = idClassVol;
	}

	@Column(name = "HORRAIREDEPART", length = 20)
	public String getHorraireDepart() {
		return horraireDepart;
	}

	public void setHorraireDepart(String horraireDepart) {
		this.horraireDepart = horraireDepart;
	}

}
